using QuickPulse.Explains;


namespace QuickTestr.Tests.Challenges;

[DocFile]
[DocContent(
"""
QuickTestr includes a number of regression tests inspired by well-known
property-based testing challenges and shrink-pathology examples.

These examples are intentionally difficult for many shrinking systems because they involve:

* recursive structures
* coupled values
* normalization problems
* monadic generation
* interdependent reductions
* duplicate coordination
* structure-preserving shrinking

The goal of these examples is not to "win benchmarks",
but to demonstrate the kinds of reductions QuickTestr can reliably produce in practice.

Most examples in this document are based on:

* long-standing QuickCheck folklore,
* Hypothesis shrinking discussions,
* test.check shrink-pathology examples,
* jqwik-related community discussions,
* and historical shrinking challenge suites.

The reports shown here are generated by QuickTestr itself.

For reproducibility, the examples currently use fixed seeds as part of the regression suite.
The seeded runs shown below represent actual QuickTestr behaviour.

The challenges in this document are taken from the following repository:

https://github.com/jlink/shrinking-challenge

The challenge descriptions are based on, and in many cases copied directly from,
the originals found there. 
""")]
public class TestrChallenges;